apiVersion: v1
kind: ServiceAccount
metadata:
 name: airflow
 namespace: develop

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: develop
  name: airflow
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods","pods/logs"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow
  namespace: develop
subjects:
- kind: ServiceAccount
  name: airflow # Name of the ServiceAccount
  namespace: develop
roleRef:
  kind: Role # This must be Role or ClusterRole
  name: airflow # This must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
