apiVersion: v1
kind: Service
metadata:
  name: master-spark
  namespace: develop
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: web-ui
    - protocol: TCP
      port: 7077
      targetPort: 7077
      name: master-spark
  selector:
    app: master-spark
---
apiVersion: v1
kind: Service
metadata:
  name: worker-spark
  namespace: develop
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
      name: worker
  selector:
    app: worker-spark
