apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: master-spark
  namespace: develop
  labels:
    app: master-spark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master-spark
  updateStrategy:
    type: RollingUpdate
  serviceName: "spark"
  template:
    metadata:
      labels:
        app: master-spark
    spec:
      containers:
      - name: master
        image: gustcol/cidacs:spark-0.0.2
        args: ["master"]
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1
            memory: 4096Mi
          requests:
            cpu: 500m
            memory: 1024Mi
        ports:
        - name: web-ui
          containerPort: 8080
        - name: master
          containerPort: 7077
      - name: jupyter
        image: gustcol/cidacs:jupyter-0.0.0
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1
            memory: 4096Mi
          requests:
            cpu: 500m
            memory: 1024Mi
        ports:
        - name: jupyter-web-ui
          containerPort: 8888
        env:
          - name: JUPYTER_ENABLE_LAB
            value: "yes"
          - name: JUPYTER_TOKEN
            value: "NiceToken"
      imagePullSecrets:
      - name: docker-login
      volumes:
      - name: spark-config
        configMap:
          name: spark-config
